name: 'Test'
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: 'Install Deps'
      run: pnpm install
    - name: 'Test'
      run: pnpm test:ci
    - name: 'Report Coverage'
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2